# Generated by Django 4.2.4 on 2023-09-19 20:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('blog_feature_image', models.ImageField(upload_to='blog/images/')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Client/images/')),
            ],
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='review_images')),
                ('review_date', models.DateField()),
                ('platform_name', models.CharField(blank=True, max_length=100, null=True)),
                ('c_image', models.ImageField(blank=True, null=True, upload_to='c_images')),
                ('review_details', models.TextField()),
                ('project_name', models.CharField(max_length=100)),
                ('has_features', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaname', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('pin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team_members/')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=100)),
                ('portfolio_feature_image', models.ImageField(upload_to='portfolio/images/')),
                ('client_name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('cover_image', models.ImageField(upload_to='portfolio/cover_images/')),
                ('overview', ckeditor.fields.RichTextField()),
                ('solution', ckeditor.fields.RichTextField()),
                ('image1', models.ImageField(upload_to='portfolio/images/')),
                ('image2', models.ImageField(upload_to='portfolio/images/')),
                ('image3', models.ImageField(upload_to='portfolio/images/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('category', models.ManyToManyField(to='backend.portfoliocategory')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.review')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.faqcategory')),
            ],
        ),
    ]
